import '../constants/assets.dart';
import '../models/listing.dart';

final seedListings = <Listing>[
  Listing(
    id: 'motorola-v60',
    title: 'Motorola',
    subtitle: 'V60',
    category: 'Phones',
    price: 1299,
    condition: 'Excellent',
    description:
        'A collector-grade Motorola V60 with iconic Y2K flip-phone attitude.',
    storage: 'SIM',
    battery: '9h',
    connector: 'Mini USB',
    imageAsset: Assets.v60,
    status: 'FEATURED',
    views: 248,
    seller: 'RetroTech Collector',
  ),
  Listing(
    id: 'ipod-classic',
    title: 'iPod Classic',
    subtitle: '4th Generation',
    category: 'Audio',
    price: 1599,
    condition: 'Used - Excellent',
    description:
        'The iconic iPod Classic 4th Gen with 40GB storage. Perfect working condition.',
    storage: '40GB',
    battery: '14h',
    connector: '30-Pin',
    imageAsset: Assets.ipodFront,
    status: 'TRENDING',
    views: 376,
  ),
  Listing(
    id: 'sony-discman',
    title: 'Sony',
    subtitle: 'Discman',
    category: 'Audio',
    price: 999,
    condition: 'Portable CD classic.',
    description: 'A transparent Discman-style player for late-Y2K audio fans.',
    storage: 'CD',
    battery: '12h',
    connector: '3.5mm',
    imageAsset: Assets.discmanHome,
    status: 'NEW ARRIVAL',
    views: 152,
    seller: 'VintageAudioCo',
  ),
  Listing(
    id: 'walkman',
    title: 'Sony Walkman',
    subtitle: 'Cassette',
    category: 'Audio',
    price: 899,
    condition: 'Collector Grade',
    description:
        'Fully tested Walkman with clean transparent body and strong playback.',
    storage: 'Tape',
    battery: 'AA',
    connector: '3.5mm',
    imageAsset: Assets.walkman,
    status: 'Available',
    views: 228,
    seller: 'VintageAudioCo',
    rating: 4.8,
    reviews: 96,
  ),
  Listing(
    id: 'minidisc',
    title: 'MiniDisc Player',
    subtitle: 'Portable',
    category: 'Audio',
    price: 749,
    condition: 'Fully Working',
    description:
        'Compact MiniDisc player with crisp buttons and rare Y2K finish.',
    storage: 'MD',
    battery: '10h',
    connector: 'Line In',
    imageAsset: Assets.minidisc,
    status: 'Published',
    views: 182,
    seller: 'PixelCam Studio',
    rating: 4.7,
    reviews: 74,
  ),
  Listing(
    id: 'gameboy',
    title: 'GameBoy Color',
    subtitle: 'Clear Shell',
    category: 'Gaming',
    price: 899,
    condition: 'Active',
    description:
        'Clear GameBoy Color with clean screen and responsive buttons.',
    storage: 'Cart',
    battery: 'AA',
    connector: 'Link',
    imageAsset: Assets.gameboy,
    status: 'Published',
    views: 194,
  ),
  Listing(
    id: 'camera',
    title: 'Compact Camera',
    subtitle: 'Transparent',
    category: 'Cameras',
    price: 699,
    condition: 'New Arrival',
    description: 'Crystal compact camera for Frutiger Aero collectors.',
    storage: 'SD',
    battery: '8h',
    connector: 'USB',
    imageAsset: Assets.camera,
    status: 'Published',
    views: 119,
  ),
  Listing(
    id: 'imac',
    title: 'iMac G3',
    subtitle: 'Blueberry',
    category: 'Computing',
    price: 2499,
    condition: 'Display Piece',
    description: 'Blue translucent iMac G3 for desk display and retro setups.',
    storage: '6GB',
    battery: 'AC',
    connector: 'USB',
    imageAsset: Assets.imac,
    status: 'Draft',
    views: 88,
  ),
  Listing(
    id: 'clear-watch',
    title: 'Clear Watch',
    subtitle: 'Digital',
    category: 'Wearables',
    price: 649,
    condition: 'Collector-ready wearable.',
    description:
        'Transparent Y2K digital watch matched to the Wearables category art.',
    storage: 'LCD',
    battery: 'Coin Cell',
    connector: 'None',
    imageAsset: Assets.watch,
    status: 'Published',
    views: 106,
    seller: 'RetroTech Collector',
    rating: 4.8,
    reviews: 52,
  ),
  Listing(
    id: 'palm',
    title: 'PalmPilot',
    subtitle: 'PDA',
    category: 'Phones',
    price: 529,
    condition: 'Working',
    description: 'Classic PalmPilot with stylus and clean monochrome screen.',
    storage: '8MB',
    battery: 'AAA',
    connector: 'Serial',
    imageAsset: Assets.palm,
    status: 'Published',
    views: 137,
    seller: 'PalmPilotFan',
  ),
];
